# Generated by Django 3.0.7 on 2020-06-11 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='website_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=250, unique=True)),
                ('title', models.CharField(max_length=250)),
                ('category', models.CharField(max_length=250)),
                ('city', models.CharField(max_length=250)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
